# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Checkmarx CxFlow Action
  # You may pin to the exact commit or the version.
  # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
        with:
          # Provide Checkmarx URL
          checkmarx_url: https://cxprivatecloud.checkmarx.net/ 
          # Select a Checkmarx Team
          team: /CxServer/SP/EMEA
          # Provide Checkmarx Username
          checkmarx_username: LeonMaister 
          # Provide Checkmarx Password
          checkmarx_password: adminADMIN1! 
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          # Select a Checkmarx Project
          project: LM_JVL
          # Select an Application Name used by downstream bug tracker systems
          #app: # optional, default is SampleApp
          # Select a Checkmarx Preset
          #preset: # optional, default is Checkmarx Default
          # Break build based on Checkmarx findings?
          #break_build: # optional
          # Bug tracker for the scan results.
          #bug_tracker: # optional, default is Sarif
          # Incremental Scans?
          #incremental: # optional, default is true
          # Additional CLI parameters
          #params: # optional, default is 
          # GitHub API Token
          #github_token: # optional, default is ${{ github.token }}
          # Vulnerability Scanners (sast, sca, ast, cxgo)
          #scanners: # default is 
          # Provide SCA API URL
          #sca_api_url: # optional, default is https://api.scacheckmarx.com
          # Provide SCA APP URL
          #sca_app_url: # optional, default is https://sca.scacheckmarx.com
          # Provide SCA Access Control URL
          #sca_access_control_url: # optional, default is https://platform.checkmarx.net
          # Provide SCA Tenant
          #sca_tenant: # optional, default is 
          # Provide SCA Username
          #sca_username: # optional, default is 
          # Provide SCA Password
          #sca_password: # optional, default is 
          # Provide CxGo Client Secret
        
